build: fix build on Solaris 10 with GCC 8.4
munmap on Solaris 10, depending on compile time defines can use caddr_t
instead of void* as its argument failing the build with the following
error message:

error: passing argument 1 of 'munmap' from incompatible pointer type

cast to void*, should be safe.